<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */

/**
 * Implements hook_menu().
 */
function islandora_test_viewer_menu() {
  return array(
    'admin/islandora/islandora_viewers/test_viewer' => array(
      'title' => 'Islandora Test Viewer',
      'description' => 'Configure the Islandora Test Viewer.',
      'page callback' => 'drupal_get_form',
      'access arguments' => array('administer site configuration'),
      'page arguments' => array('islandora_test_viewer_admin'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function islandora_test_viewer_theme() {
  return array(
    // This item should match the corresponding item in
    // hook_islandora_viewer_info().
    'islandora_test_viewer' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-test-viewer',
      'variables' => array(
        'islandora_object' => NULL,
      ),
    ),
  );
}

/**
 * Implements hook_islandora_viewer_info().
 */
function islandora_test_viewer_islandora_viewer_info() {
  $mimetype = variable_get('islandora_test_viewer_mimetype', '');
  $cmodel = variable_get('islandora_test_viewer_cmodel', '');
  return array(
    // This item should match the corresponding item in hook_theme().
    'islandora_test_viewer' => array(
      'label' => t('Islandora Test Viewer'),
      'description' => t('A simple test viewer for Islandora.'),
      'configuration' => 'admin/islandora/islandora_viewers/test_viewer',
      'callback' => 'islandora_test_viewer_callback',
      'model' => array(
        $cmodel,
      ),
      'mimetype' => array($mimetype,
      ),
    ),
  );
}

/**
 * Callback function for the viewer.
 *
 * @param array $params
 *   The params for the theme function 'islandora_simple_xml_viewer'.
 * @param IslandoraFedoraObject $islandora_object
 *   The object that we are viewing.
 *
 * @return string
 *   HTML representation of the Islandora Test Viewer.
 */
function islandora_test_viewer_callback(array $params, IslandoraFedoraObject $islandora_object = NULL) {
  $mimetype = variable_get('islandora_test_viewer_mimetype', '');
  $dsid = variable_get('islandora_test_viewer_dsid', 'OBJ');
  if (isset($islandora_object[$dsid]) && $islandora_object['OBJ']->mimetype == $mimetype) {
    if (islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $islandora_object[$dsid])) {
      return theme('islandora_test_viewer', array('islandora_object' => $islandora_object));
    }
  }
}
